# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

City:
  fields:
    default: name, lat, long, zoom, country_id, subdomain, country
    form: name, lat, long, zoom, country_id, subdomain, country
  order_by: 
  relationships: country, reports
  filters: created_at
  search: name
  application: fixmystreet

Country:
  fields:
    default: name, lat, long, zoom, default_city_id
    form: name, lat, long, zoom, default_city_id
  order_by: 
  relationships: cities, default_city
  filters: created_at
  search: name
  application: fixmystreet

Report:
  fields:
    default: title, description, latitude, longtitude, user_id, photo1_file_name, photo2_file_name, photo3_file_name, photo4_file_name, photo5_file_name, status, video_url, city_id, user, city
    form: title, description, latitude, longtitude, user_id, photo1_file_name, photo2_file_name, photo3_file_name, photo4_file_name, photo5_file_name, status, video_url, city_id, user, city
  order_by: 
  relationships: city, user
  filters: created_at
  search: title
  application: fixmystreet

Role:
  fields:
    default: name
    form: name
  order_by: 
  relationships: users
  filters: created_at
  search: name
  application: fixmystreet

User:
  fields:
    default: email, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, facebook_id, twitter_id, link, name, gender, facebook, twitter
    form: email, reset_password_token, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, facebook_id, twitter_id, link, name, gender, facebook, twitter
  order_by: 
  relationships: reports, roles
  filters: created_at
  search: name
  application: fixmystreet

