# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  City: create, read, update, delete
  Country: create, read, update, delete
  Report: create, read, update, delete
  Role: create, read, update, delete
  User: create, read, update, delete
